
package klevalto.exeptions;

import javax.xml.ws.WebFault;

import yousign.authenticationWS.wsdl.YousignException;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "YousignException", targetNamespace = "http://www.yousign.com")
public class YousignException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private YousignException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public YousignException_Exception(String message, YousignException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public YousignException_Exception(String message, YousignException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.yousign.YousignException
     */
    public YousignException getFaultInfo() {
        return faultInfo;
    }

}
